on:
  pull_request:
    types: [opened, synchronize]
    
jobs:
  eslint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v1.4.4
        with:
          node-version: 12
      - name: npm install
        run: npm install
      - name: ESLint
        run: npm run lint 
      - name: Check commits
        uses: wagoid/commitlint-github-action@v3
      - name: Check Tests
        run: npm rum test 

        
